### PR TITLE
[Feature #159617783] Added Sign-Up page

### PR DESCRIPTION
**Pull request by Tony-Ndichu**
**What does this Pull Request do?**
This pull request creates the Sign-Up page for unregistered users to be able to create their accounts.

**How to test it**
```
$ git clone
$ git checkout UI

```

- Navigate UI folder

- Open Sign-Up.html

**Relevant pivot tracker story**
[#159617783](https://www.pivotaltracker.com/n/projects/2189533)

**Relevant screenshot for the page**
screenshot 73

### CODE REVIEW

**Comment by evamaina** [comment]
Nice landing page

**Comment by TheSteelGuy** [comment]
One should switch to the branch with signup.htm before anything else ie by typing **git checkout ui**
for them to see the signup.html

**Comment by TheSteelGuy** [comment]
Cool design

**Comment by Tony-Ndichu** [comment]
@TheSteelGuy , is that in regard to cloning the project? Am alittle lost on what you mean.

**Pull request closed without merging**
